version: '3'
services:
  golangproject:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - rabbitmq

  mongodb:
    image: mongo
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672